openapi: 3.0.0
info:
  title: Sales Inventory System API
  description: API for sales inventory system
  version: 0.0.1

servers:
  - url: http://localhost:3090

tags:
  - Auth
  - Health
  - Users
  - Position

paths:
  /auth:
    post:
      tags:
        - Auth
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  description: The username of the user
                  example: 'john_doe'
                password:
                  type: string
                  description: The password of the user
                  example: 'p@ssw0rd'
              required:
                - userName
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Login message
                    example: Login Successful
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                    example: 'Invalid username or password'
  /position:
    get:
      tags:
        - Position
      summary: Get all positions
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Position ID
                      example: 100021
                    name:
                      type: string
                      description: Position Name
                      example: Manager
                    createdAt:
                      type: string
                      description: Position Created At
                      example: '2024-08-31 14:42'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                    example: 'Error retrieving positions'
